import React, { useState } from 'react';
import { 
  X, 
  AlertTriangle, 
  CheckCircle2, 
  Terminal, 
  Copy, 
  Check, 
  Layers, 
  ShieldAlert, 
  Wrench, 
  Server, 
  Database, 
  Globe, 
  Lock, 
  ArrowRight,
  Zap,
  HelpCircle,
  FileCode,
  Sparkles,
  ExternalLink
} from 'lucide-react';
import { Website, CheckLog, ErrorDiagnosis } from '../types';
import { diagnoseWebsiteError, DIAGNOSTIC_SCENARIOS, DiagnosticScenario } from '../utils/errorDiagnostics';

interface ErrorDiagnosticsModalProps {
  website: Website | null;
  isOpen: boolean;
  onClose: () => void;
  onCheckNow: (id: number) => void;
  onCreateTicketFromDiagnosis?: (websiteId: number, subject: string, description: string) => void;
}

export const ErrorDiagnosticsModal: React.FC<ErrorDiagnosticsModalProps> = ({
  website,
  isOpen,
  onClose,
  onCheckNow,
  onCreateTicketFromDiagnosis
}) => {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [copiedReport, setCopiedReport] = useState(false);
  const [selectedScenario, setSelectedScenario] = useState<DiagnosticScenario | null>(null);

  if (!isOpen || !website) return null;

  // Compute diagnosis based on real website status or interactive simulated scenario
  const effectiveLog: CheckLog | null = selectedScenario ? {
    id: 99999,
    website_id: website.id,
    is_up: selectedScenario.simulatedLog.is_up,
    status_code: selectedScenario.simulatedLog.status_code,
    response_time_ms: selectedScenario.simulatedLog.response_time_ms,
    error_message: selectedScenario.simulatedLog.error_message,
    checked_at: 'Just now (Simulated Test)'
  } : (website.logs[0] || null);

  const diagnosis = diagnoseWebsiteError(website, effectiveLog);
  const isHealthy = !diagnosis && effectiveLog && effectiveLog.is_up;

  const handleCopyCommand = (text: string, idx: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const handleCopyFullReport = () => {
    if (!diagnosis) return;
    const reportText = `[ChrisTech Root Cause & Fix Report]
Target Website: ${website.name} (${website.url})
Status: ERROR DETECTED
Error Layer: ${diagnosis.layerTitle}
Component: ${diagnosis.sourceComponent}
HTTP Status: ${effectiveLog?.status_code || 'None'}
Latency: ${effectiveLog?.response_time_ms || 0}ms

ROOT CAUSE (Where is it coming from?):
${diagnosis.rootCause}

POSSIBLE REASONS:
${diagnosis.possibleReasons.map(r => `• ${r}`).join('\n')}

HOW TO FIX (Remediation Steps):
${diagnosis.remediationSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

TERMINAL REMEDIATION COMMANDS:
${diagnosis.remediationCommands.join('\n\n')}

PREVENTION ADVICE:
${diagnosis.preventionTips.map(t => `• ${t}`).join('\n')}
Generated by ChrisTech Health Sentinel.`;

    navigator.clipboard.writeText(reportText);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  const handleCreateTicket = () => {
    if (!diagnosis || !onCreateTicketFromDiagnosis) return;
    const subject = `[Incident Fix Guide] ${website.name}: ${diagnosis.layerTitle} failure`;
    const description = `AUTOMATED ROOT CAUSE DIAGNOSIS & REMEDIATION PLAN:

Where is it coming from?
- Layer: ${diagnosis.layerTitle}
- Component: ${diagnosis.sourceComponent}
- Error Detail: ${effectiveLog?.error_message || 'N/A'}
- Root Cause: ${diagnosis.rootCause}

How to fix it:
${diagnosis.remediationSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

Remediation Commands to run on server:
\`\`\`bash
${diagnosis.remediationCommands.join('\n')}
\`\`\`

Generated automatically by ChrisTech Diagnostic Engine.`;

    onCreateTicketFromDiagnosis(website.id, subject, description);
    onClose();
  };

  // Architectural layers for visualization
  const ARCH_LAYERS = [
    { key: 'dns', label: '1. DNS', icon: Globe },
    { key: 'ssl_tls', label: '2. TLS/SSL', icon: Lock },
    { key: 'auth_waf', label: '3. WAF / Edge', icon: ShieldAlert },
    { key: 'gateway_proxy', label: '4. Proxy Gateway', icon: Server },
    { key: 'application_server', label: '5. App Backend', icon: FileCode },
    { key: 'database_storage', label: '6. Database', icon: Database },
    { key: 'dom_content', label: '7. DOM Render', icon: Sparkles }
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/80 backdrop-blur-xs overflow-y-auto">
      <div 
        id="error-diagnostics-modal"
        className="w-full max-w-4xl max-h-[92vh] bg-slate-900 border border-slate-800 rounded-xl shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/70">
          <div className="flex items-center gap-3">
            <div className={`p-2.5 rounded-lg border flex items-center justify-center ${
              isHealthy
                ? 'bg-emerald-950/70 text-emerald-400 border-emerald-800/60'
                : 'bg-rose-950/70 text-rose-400 border-rose-800/60'
            }`}>
              {isHealthy ? <CheckCircle2 className="w-5 h-5" /> : <AlertTriangle className="w-5 h-5 animate-pulse" />}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-bold text-white tracking-tight">Root Cause & Diagnostic Remediation</h2>
                <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full ${
                  isHealthy
                    ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                    : 'bg-rose-500/10 text-rose-400 border border-rose-500/20'
                }`}>
                  {isHealthy ? 'Healthy - No Outage' : 'Incident Diagnosed'}
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Analyzing <span className="text-slate-200 font-semibold">{website.name}</span> ({website.url})
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyFullReport}
              disabled={isHealthy}
              className="hidden sm:inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg border border-slate-700 transition disabled:opacity-40"
              title="Copy diagnosis and fix guide to clipboard"
            >
              {copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedReport ? 'Copied Report' : 'Copy Report'}</span>
            </button>

            <button
              onClick={() => {
                setSelectedScenario(null);
                onCheckNow(website.id);
              }}
              className="px-3 py-1.5 text-xs font-semibold bg-blue-600 hover:bg-blue-500 text-white rounded-lg flex items-center gap-1.5 transition"
              title="Re-ping the live website to verify fix"
            >
              <Zap className="w-3.5 h-3.5" />
              <span>Verify Fix Now</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white rounded-lg transition ml-1"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          
          {/* Architectural Layer Pipeline Visualization */}
          <div className="bg-slate-950/60 border border-slate-800 rounded-xl p-4">
            <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-3 flex items-center justify-between">
              <span>Architectural Diagnostic Pipeline</span>
              <span className="text-[10px] font-normal text-slate-500">Highlighted step shows failure origin</span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2">
              {ARCH_LAYERS.map((layer) => {
                const IconComponent = layer.icon;
                const isFailing = diagnosis && diagnosis.layer === layer.key;
                return (
                  <div
                    key={layer.key}
                    className={`p-2.5 rounded-lg border text-center transition flex flex-col items-center justify-center gap-1 ${
                      isFailing
                        ? 'bg-rose-950/80 border-rose-600 text-rose-300 ring-2 ring-rose-500/30'
                        : isHealthy
                          ? 'bg-emerald-950/20 border-emerald-900/40 text-emerald-400'
                          : 'bg-slate-900/80 border-slate-800 text-slate-400'
                    }`}
                  >
                    <IconComponent className={`w-4 h-4 ${isFailing ? 'text-rose-400 animate-bounce' : 'text-slate-400'}`} />
                    <span className="text-[11px] font-bold leading-tight">{layer.label}</span>
                    <span className="text-[9px] font-mono">
                      {isFailing ? 'CRITICAL FAIL' : isHealthy ? 'PASSING' : 'READY'}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          {/* If No Error Is Present */}
          {isHealthy && (
            <div className="p-6 bg-emerald-950/30 border border-emerald-800/40 rounded-xl text-center space-y-3">
              <div className="w-12 h-12 rounded-full bg-emerald-500/20 text-emerald-400 mx-auto flex items-center justify-center">
                <CheckCircle2 className="w-7 h-7" />
              </div>
              <h3 className="text-base font-bold text-white">All Systems Operational & Healthy</h3>
              <p className="text-xs text-slate-300 max-w-lg mx-auto">
                No active error detected for <span className="font-semibold text-emerald-300">{website.name}</span>. HTTP status code is 200, response latency is within healthy thresholds ({effectiveLog?.response_time_ms}ms), and keyword checks are passing.
              </p>
              <div className="pt-2">
                <p className="text-[11px] text-slate-400 mb-2">Want to see how ChrisTech diagnoses real failures?</p>
                <div className="flex flex-wrap items-center justify-center gap-2">
                  {DIAGNOSTIC_SCENARIOS.slice(0, 4).map(sc => (
                    <button
                      key={sc.id}
                      onClick={() => setSelectedScenario(sc)}
                      className="px-2.5 py-1 text-[11px] bg-slate-800 hover:bg-slate-700 text-blue-300 border border-slate-700 rounded-md transition"
                    >
                      Simulate: {sc.name.split('(')[0]}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* If Error IS Present: Root Cause + Fix */}
          {diagnosis && (
            <div className="space-y-6">
              {/* Card 1: Where is the error coming from? */}
              <div className="bg-slate-950/50 border border-rose-900/40 rounded-xl p-5 shadow-lg space-y-4">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-2.5">
                    <div className="p-2 rounded-lg bg-rose-500/10 text-rose-400 border border-rose-500/20">
                      <Layers className="w-4 h-4" />
                    </div>
                    <div>
                      <span className="text-[10px] font-extrabold uppercase tracking-widest text-rose-400">
                        1. Where is the error coming from?
                      </span>
                      <h3 className="text-base font-bold text-white">{diagnosis.layerTitle}</h3>
                    </div>
                  </div>

                  <span className="px-2.5 py-1 rounded text-xs font-bold font-mono uppercase tracking-wider bg-rose-900/60 text-rose-300 border border-rose-700/60">
                    Severity: {diagnosis.severity}
                  </span>
                </div>

                {/* Specific Source Component */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-1">
                  <div className="p-3 bg-slate-900/80 border border-slate-800 rounded-lg">
                    <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Faulty Component / Origin</div>
                    <div className="text-xs font-semibold text-rose-300 font-mono">
                      {diagnosis.sourceComponent}
                    </div>
                  </div>

                  <div className="p-3 bg-slate-900/80 border border-slate-800 rounded-lg">
                    <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Observed Error Signal</div>
                    <div className="text-xs font-semibold text-slate-200 font-mono truncate">
                      {effectiveLog?.status_code ? `HTTP ${effectiveLog.status_code}` : 'No HTTP Code'} &bull; {effectiveLog?.error_message || 'Timeout / Connection Dropped'}
                    </div>
                  </div>
                </div>

                {/* Root Cause Details */}
                <div className="p-3.5 bg-slate-900/90 border border-slate-800/90 rounded-lg text-xs text-slate-200 leading-relaxed">
                  <span className="font-bold text-white block mb-1">Root Cause Explanation:</span>
                  {diagnosis.rootCause}
                </div>

                {/* Possible reasons checklist */}
                <div>
                  <div className="text-[11px] font-bold text-slate-300 uppercase tracking-wider mb-2">
                    Probable Failure Triggers:
                  </div>
                  <ul className="space-y-1.5">
                    {diagnosis.possibleReasons.map((reason, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-xs text-slate-300">
                        <span className="text-rose-400 font-bold">&bull;</span>
                        <span>{reason}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Card 2: How can it be fixed? */}
              <div className="bg-slate-950/50 border border-blue-900/40 rounded-xl p-5 shadow-lg space-y-4">
                <div className="flex items-center gap-2.5">
                  <div className="p-2 rounded-lg bg-blue-500/10 text-blue-400 border border-blue-500/20">
                    <Wrench className="w-4 h-4" />
                  </div>
                  <div>
                    <span className="text-[10px] font-extrabold uppercase tracking-widest text-blue-400">
                      2. How can it be fixed?
                    </span>
                    <h3 className="text-base font-bold text-white">Actionable Remediation & Server Commands</h3>
                  </div>
                </div>

                {/* Step-by-step checklist */}
                <div className="space-y-2">
                  <div className="text-[11px] font-bold text-slate-300 uppercase tracking-wider">
                    Recommended Fix Procedure:
                  </div>
                  <div className="space-y-2">
                    {diagnosis.remediationSteps.map((step, idx) => (
                      <div key={idx} className="flex items-start gap-2.5 p-2.5 rounded-lg bg-slate-900/80 border border-slate-800/80">
                        <span className="w-5 h-5 rounded-full bg-blue-950 text-blue-400 border border-blue-800/60 font-bold text-xs flex items-center justify-center shrink-0">
                          {idx + 1}
                        </span>
                        <span className="text-xs text-slate-200 leading-snug">{step}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Shell commands with copy buttons */}
                {diagnosis.remediationCommands.length > 0 && (
                  <div className="space-y-2 pt-2">
                    <div className="flex items-center justify-between text-[11px] font-bold text-slate-300 uppercase tracking-wider">
                      <span className="flex items-center gap-1.5">
                        <Terminal className="w-3.5 h-3.5 text-cyan-400" />
                        <span>Terminal Remediation Commands</span>
                      </span>
                      <span className="text-[10px] text-slate-500 font-normal">Click to copy command</span>
                    </div>

                    <div className="space-y-2">
                      {diagnosis.remediationCommands.map((cmd, idx) => (
                        <div key={idx} className="relative group bg-slate-900 border border-slate-800 rounded-lg p-3 font-mono text-xs text-slate-200 overflow-x-auto">
                          <pre className="whitespace-pre-wrap">{cmd}</pre>
                          <button
                            onClick={() => handleCopyCommand(cmd, idx)}
                            className="absolute top-2 right-2 p-1.5 rounded-md bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition"
                            title="Copy command"
                          >
                            {copiedIndex === idx ? (
                              <Check className="w-3.5 h-3.5 text-emerald-400" />
                            ) : (
                              <Copy className="w-3.5 h-3.5" />
                            )}
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Configuration File Suggestions */}
                {diagnosis.configFileSuggestions && diagnosis.configFileSuggestions.length > 0 && (
                  <div className="space-y-2 pt-2">
                    <div className="text-[11px] font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                      <FileCode className="w-3.5 h-3.5 text-amber-400" />
                      <span>Config File Blueprint</span>
                    </div>
                    {diagnosis.configFileSuggestions.map((cfg, idx) => (
                      <div key={idx} className="bg-slate-900 border border-slate-800 rounded-lg p-3 font-mono text-xs text-amber-300/90 overflow-x-auto">
                        <pre className="whitespace-pre-wrap">{cfg}</pre>
                      </div>
                    ))}
                  </div>
                )}

                {/* Future Prevention Tips */}
                <div className="pt-2 border-t border-slate-800/80">
                  <div className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">
                    How to prevent this in the future:
                  </div>
                  <ul className="space-y-1">
                    {diagnosis.preventionTips.map((tip, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-xs text-slate-400">
                        <CheckCircle2 className="w-3.5 h-3.5 text-blue-400 shrink-0 mt-0.5" />
                        <span>{tip}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Bottom Quick Actions: Create Incident Ticket */}
              {onCreateTicketFromDiagnosis && (
                <div className="p-4 bg-slate-950/80 border border-slate-800 rounded-xl flex flex-col sm:flex-row items-center justify-between gap-3">
                  <div>
                    <div className="text-xs font-bold text-white">Need your team or developer to handle this?</div>
                    <div className="text-[11px] text-slate-400">
                      Instantly turn this root cause diagnosis and fix commands into an assigned Support Incident Ticket.
                    </div>
                  </div>
                  <button
                    onClick={handleCreateTicket}
                    className="w-full sm:w-auto px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-lg shadow transition flex items-center justify-center gap-2"
                  >
                    <span>Create Ticket with Fix Guide</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              )}
            </div>
          )}

          {/* Test & Simulation Sandbox Selector */}
          <div className="pt-4 border-t border-slate-800">
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs font-bold text-slate-300 flex items-center gap-1.5">
                <HelpCircle className="w-3.5 h-3.5 text-blue-400" />
                <span>Test Different Error Types in Diagnostic Engine</span>
              </span>
              {selectedScenario && (
                <button
                  onClick={() => setSelectedScenario(null)}
                  className="text-[11px] text-blue-400 hover:text-blue-300 underline"
                >
                  Reset to Actual Live Status
                </button>
              )}
            </div>
            
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {DIAGNOSTIC_SCENARIOS.map((sc) => {
                const isCurrent = selectedScenario?.id === sc.id;
                return (
                  <button
                    key={sc.id}
                    onClick={() => setSelectedScenario(sc)}
                    className={`p-2.5 rounded-lg border text-left transition text-xs ${
                      isCurrent
                        ? 'bg-blue-950/90 border-blue-600 text-blue-200'
                        : 'bg-slate-900/60 border-slate-800 text-slate-300 hover:bg-slate-800/80'
                    }`}
                  >
                    <div className="font-bold truncate text-[11px]">{sc.name}</div>
                    <div className="text-[10px] text-slate-500 line-clamp-1 mt-0.5">{sc.description}</div>
                  </button>
                );
              })}
            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-950/60 flex items-center justify-between text-xs">
          <div className="text-slate-500 font-mono text-[11px]">
            {selectedScenario ? (
              <span className="text-amber-400 font-semibold">Active Simulation: {selectedScenario.name}</span>
            ) : (
              <span>Live Monitor Status: {website.logs[0]?.is_up ? 'UP' : 'DOWN'}</span>
            )}
          </div>
          <button
            onClick={onClose}
            className="px-4 py-1.5 text-xs text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-lg transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
