-- Sleek Sisters checkout: delivery options, guest tracking, M-Pesa secrets.

CREATE TABLE IF NOT EXISTS public.delivery_options (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  eta text NOT NULL DEFAULT '',
  fee numeric(12, 2) NOT NULL DEFAULT 0 CHECK (fee >= 0),
  requires_address boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS delivery_option_id integer REFERENCES public.delivery_options(id),
  ADD COLUMN IF NOT EXISTS gift_message text,
  ADD COLUMN IF NOT EXISTS fulfillment_type text;

ALTER TABLE public.payments
  ADD COLUMN IF NOT EXISTS stk_requested_at timestamptz;

CREATE UNIQUE INDEX IF NOT EXISTS payments_checkout_request_id_uidx
  ON public.payments (checkout_request_id)
  WHERE checkout_request_id IS NOT NULL;

INSERT INTO public.delivery_options (
  slug, name, description, eta, fee, requires_address, sort_order, active
) VALUES
  (
    'pickup',
    'Collect in Nairobi',
    'Collect from Sleek Sisters. We will confirm the exact point after your order.',
    'Same day once paid',
    0,
    false,
    10,
    true
  ),
  (
    'nairobi_cbd',
    'Nairobi CBD',
    'Town, Kencom, OTC, River Road and nearby offices.',
    'Same day or next day',
    200,
    true,
    20,
    true
  ),
  (
    'nairobi_estate',
    'Nairobi estates',
    'Westlands, Kilimani, Kileleshwa, Lavington, South B, South C, Embakasi and similar.',
    '1–2 days',
    300,
    true,
    30,
    true
  ),
  (
    'nairobi_satellite',
    'Greater Nairobi',
    'Ruiru, Kitengela, Ngong, Kikuyu, Athi River, Syokimau and nearby towns.',
    '1–2 days',
    450,
    true,
    40,
    true
  ),
  (
    'upcountry',
    'Rest of Kenya',
    'Sent by courier or G4S. Tracking details follow after dispatch.',
    '2–5 days',
    550,
    true,
    50,
    true
  )
ON CONFLICT (slug) DO UPDATE
SET
  name = excluded.name,
  description = excluded.description,
  eta = excluded.eta,
  fee = excluded.fee,
  requires_address = excluded.requires_address,
  sort_order = excluded.sort_order,
  active = true,
  updated_at = now();

INSERT INTO public.settings (category, setting_key, setting_value, description)
VALUES
  ('general', 'whatsapp_number', to_jsonb('0143074416'::text), 'Customer WhatsApp number'),
  (
    'general',
    'pickup_address',
    to_jsonb('Nairobi — we confirm the exact collection point after you order.'::text),
    'Store pickup note shown at checkout'
  )
ON CONFLICT (category, setting_key) DO NOTHING;

UPDATE public.settings
SET setting_value = to_jsonb('Sleek Sisters'::text),
    updated_at = now()
WHERE category = 'payments'
  AND setting_key = 'mpesa_account_name'
  AND coalesce(setting_value #>> '{}', '') ILIKE '%jawabu%';

CREATE TABLE IF NOT EXISTS private.mpesa_provider_config (
  id integer PRIMARY KEY,
  environment text NOT NULL DEFAULT 'sandbox',
  consumer_key text,
  consumer_secret text,
  shortcode text,
  passkey text,
  party_type text NOT NULL DEFAULT 'till',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO private.mpesa_provider_config (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

REVOKE ALL ON TABLE private.mpesa_provider_config FROM PUBLIC;

ALTER TABLE public.delivery_options ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS delivery_options_staff_all ON public.delivery_options;
CREATE POLICY delivery_options_staff_all
  ON public.delivery_options
  FOR ALL
  TO authenticated
  USING (public.is_staff())
  WITH CHECK (public.is_staff());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.delivery_options TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.delivery_options_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_prefix text;
BEGIN
  IF NEW.order_number IS NULL OR NEW.order_number = '' THEN
    SELECT coalesce(
      nullif(trim(s.setting_value #>> '{}'), ''),
      'SS'
    )
    INTO v_prefix
    FROM public.settings s
    WHERE (s.category = 'orders' AND s.setting_key = 'order_prefix')
       OR (s.category = 'general' AND s.setting_key = 'order_prefix')
    ORDER BY CASE WHEN s.category = 'orders' THEN 0 ELSE 1 END
    LIMIT 1;

    v_prefix := regexp_replace(coalesce(v_prefix, 'SS'), '[^A-Za-z0-9]', '', 'g');
    IF v_prefix = '' THEN
      v_prefix := 'SS';
    END IF;

    NEW.order_number :=
      upper(v_prefix) || '-' ||
      lpad(nextval('order_number_seq')::text, 6, '0');
  END IF;

  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_storefront_commerce()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'private'
AS $function$
DECLARE
  cfg private.mpesa_provider_config%ROWTYPE;
  v_stk boolean := false;
BEGIN
  SELECT * INTO cfg FROM private.mpesa_provider_config WHERE id = 1;

  v_stk :=
    coalesce(cfg.consumer_key, '') <> ''
    AND coalesce(cfg.consumer_secret, '') <> ''
    AND coalesce(cfg.shortcode, '') <> ''
    AND coalesce(cfg.passkey, '') <> '';

  RETURN jsonb_build_object(
    'whatsapp_number', coalesce((
      SELECT nullif(trim(setting_value #>> '{}'), '')
      FROM public.settings
      WHERE category = 'general' AND setting_key = 'whatsapp_number'
    ), (
      SELECT nullif(trim(setting_value #>> '{}'), '')
      FROM public.settings
      WHERE category = 'general' AND setting_key IN ('business_phone', 'phone')
      LIMIT 1
    ), '0143074416'),
    'pickup_address', coalesce((
      SELECT nullif(trim(setting_value #>> '{}'), '')
      FROM public.settings
      WHERE category = 'general' AND setting_key = 'pickup_address'
    ), 'Nairobi'),
    'phone', coalesce((
      SELECT nullif(trim(setting_value #>> '{}'), '')
      FROM public.settings
      WHERE category = 'general' AND setting_key IN ('business_phone', 'phone')
      ORDER BY CASE WHEN setting_key = 'business_phone' THEN 0 ELSE 1 END
      LIMIT 1
    ), '0143074416'),
    'mpesa', jsonb_build_object(
      'enabled', coalesce((
        SELECT (setting_value)
        FROM public.settings
        WHERE category = 'payments' AND setting_key = 'mpesa_enabled'
      ), 'true'::jsonb) IN ('true'::jsonb, to_jsonb(true)),
      'till', coalesce((
        SELECT nullif(trim(setting_value #>> '{}'), '')
        FROM public.settings WHERE category = 'payments' AND setting_key = 'mpesa_till'
      ), ''),
      'paybill', coalesce((
        SELECT nullif(trim(setting_value #>> '{}'), '')
        FROM public.settings WHERE category = 'payments' AND setting_key = 'mpesa_paybill'
      ), ''),
      'account_name', coalesce((
        SELECT nullif(trim(setting_value #>> '{}'), '')
        FROM public.settings WHERE category = 'payments' AND setting_key = 'mpesa_account_name'
      ), 'Sleek Sisters'),
      'stk_ready', v_stk
    ),
    'delivery_options', coalesce((
      SELECT jsonb_agg(to_jsonb(d) ORDER BY d.sort_order, d.id)
      FROM (
        SELECT id, slug, name, description, eta, fee, requires_address, sort_order
        FROM public.delivery_options
        WHERE active = true
        ORDER BY sort_order, id
      ) d
    ), '[]'::jsonb)
  );
END;
$function$;

DROP FUNCTION IF EXISTS public.create_checkout_order(text, text, text, text, text, text, text, jsonb, text);

CREATE OR REPLACE FUNCTION public.create_checkout_order(
  p_first_name text,
  p_last_name text,
  p_phone text,
  p_email text,
  p_delivery_option_id integer,
  p_delivery_address text,
  p_city text,
  p_payment_method text,
  p_items jsonb,
  p_gift_message text DEFAULT NULL,
  p_transaction_id text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_order_id integer;
  v_order_number text;
  v_subtotal numeric := 0;
  v_delivery_fee numeric := 0;
  v_total numeric := 0;
  v_item jsonb;
  v_product_id integer;
  v_quantity integer;
  v_price numeric;
  v_stock integer;
  v_option public.delivery_options%ROWTYPE;
  v_address text;
  v_city text;
  v_phone text;
  v_notes text;
  v_fulfillment text;
  v_gift text;
BEGIN
  v_phone := public.normalize_ke_phone(p_phone);
  IF v_phone IS NULL THEN
    RAISE EXCEPTION 'Enter a valid Kenyan phone number';
  END IF;

  IF nullif(trim(p_first_name), '') IS NULL
     OR nullif(trim(p_last_name), '') IS NULL
     OR nullif(trim(p_email), '') IS NULL THEN
    RAISE EXCEPTION 'Name and email are required';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Cart is empty';
  END IF;

  SELECT * INTO v_option
  FROM public.delivery_options
  WHERE id = p_delivery_option_id AND active = true;

  IF v_option.id IS NULL THEN
    RAISE EXCEPTION 'Choose a delivery option';
  END IF;

  v_delivery_fee := coalesce(v_option.fee, 0);
  v_fulfillment := CASE WHEN v_option.requires_address THEN 'delivery' ELSE 'pickup' END;
  v_gift := nullif(trim(p_gift_message), '');

  IF v_option.requires_address THEN
    v_address := nullif(trim(p_delivery_address), '');
    v_city := nullif(trim(p_city), '');
    IF v_address IS NULL OR v_city IS NULL THEN
      RAISE EXCEPTION 'Delivery address and town are required';
    END IF;
  ELSE
    v_address := coalesce(nullif(trim(p_delivery_address), ''), (
      SELECT coalesce(nullif(trim(setting_value #>> '{}'), ''), 'Nairobi')
      FROM public.settings
      WHERE category = 'general' AND setting_key = 'pickup_address'
      LIMIT 1
    ), 'Nairobi pickup');
    v_city := coalesce(nullif(trim(p_city), ''), 'Nairobi');
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id := (v_item->>'product_id')::integer;
    v_quantity := (v_item->>'quantity')::integer;

    IF v_quantity IS NULL OR v_quantity < 1 THEN
      RAISE EXCEPTION 'Invalid product quantity';
    END IF;

    SELECT price, stock_quantity INTO v_price, v_stock
    FROM public.products
    WHERE id = v_product_id
    FOR UPDATE;

    IF v_price IS NULL THEN
      RAISE EXCEPTION 'Product % does not exist', v_product_id;
    END IF;

    IF coalesce(v_stock, 0) < v_quantity THEN
      RAISE EXCEPTION 'Not enough stock for product %', v_product_id;
    END IF;

    v_subtotal := v_subtotal + (v_price * v_quantity);
  END LOOP;

  IF v_subtotal <= 0 THEN
    v_delivery_fee := 0;
  END IF;

  v_total := v_subtotal + v_delivery_fee;
  v_notes := 'Order placed on the Sleek Sisters shop · ' || v_option.name;
  IF v_gift IS NOT NULL THEN
    v_notes := v_notes || E'\nGift note: ' || v_gift;
  END IF;

  INSERT INTO public.orders (
    total_amount, status, payment_status, payment_method,
    first_name, last_name, phone, email, delivery_address, city,
    delivery_fee, notes, auth_user_id, sales_channel,
    delivery_option_id, gift_message, fulfillment_type
  ) VALUES (
    v_total, 'pending', 'pending',
    coalesce(nullif(trim(p_payment_method), ''), 'M-Pesa'),
    trim(p_first_name), trim(p_last_name), v_phone, trim(p_email),
    v_address, v_city, v_delivery_fee,
    v_notes,
    auth.uid(), 'online',
    v_option.id, v_gift, v_fulfillment
  ) RETURNING id, order_number INTO v_order_id, v_order_number;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id := (v_item->>'product_id')::integer;
    v_quantity := (v_item->>'quantity')::integer;
    SELECT price INTO v_price FROM public.products WHERE id = v_product_id;

    INSERT INTO public.order_items (order_id, product_id, quantity, price_at_purchase)
    VALUES (v_order_id, v_product_id, v_quantity, v_price);

    UPDATE public.products
    SET stock_quantity = stock_quantity - v_quantity, updated_at = now()
    WHERE id = v_product_id;
  END LOOP;

  INSERT INTO public.payments (
    order_id, amount, payment_method, transaction_id, status, phone
  ) VALUES (
    v_order_id, v_total,
    coalesce(nullif(trim(p_payment_method), ''), 'M-Pesa'),
    nullif(trim(p_transaction_id), ''),
    'pending',
    v_phone
  );

  RETURN jsonb_build_object(
    'ok', true,
    'order_id', v_order_id,
    'order_number', v_order_number,
    'subtotal', v_subtotal,
    'delivery_fee', v_delivery_fee,
    'total', v_total,
    'payment_status', 'pending',
    'delivery_name', v_option.name,
    'fulfillment_type', v_fulfillment
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.track_guest_order(p_order_number text, p_phone text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_phone text;
  v_ref text;
  v_order public.orders%ROWTYPE;
  v_items jsonb;
BEGIN
  v_phone := public.normalize_ke_phone(p_phone);
  v_ref := upper(trim(coalesce(p_order_number, '')));

  IF v_phone IS NULL OR v_ref = '' THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Enter your order number and the phone used at checkout.');
  END IF;

  SELECT * INTO v_order
  FROM public.orders o
  WHERE public.normalize_ke_phone(o.phone) = v_phone
    AND (
      upper(o.order_number) = v_ref
      OR (
        v_ref ~ '^[0-9]+$'
        AND o.id = v_ref::integer
      )
    )
  ORDER BY o.id DESC
  LIMIT 1;

  IF v_order.id IS NULL THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', 'No order matched that number and phone. Check both and try again.'
    );
  END IF;

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'name', coalesce(p.name, 'Item'),
    'quantity', oi.quantity,
    'price', oi.price_at_purchase
  ) ORDER BY oi.id), '[]'::jsonb)
  INTO v_items
  FROM public.order_items oi
  LEFT JOIN public.products p ON p.id = oi.product_id
  WHERE oi.order_id = v_order.id;

  RETURN jsonb_build_object(
    'ok', true,
    'order', jsonb_build_object(
      'order_id', v_order.id,
      'order_number', v_order.order_number,
      'status', v_order.status,
      'payment_status', v_order.payment_status,
      'payment_method', v_order.payment_method,
      'first_name', v_order.first_name,
      'fulfillment_type', v_order.fulfillment_type,
      'city', v_order.city,
      'delivery_address', v_order.delivery_address,
      'delivery_fee', v_order.delivery_fee,
      'total_amount', v_order.total_amount,
      'gift_message', v_order.gift_message,
      'created_at', v_order.created_at,
      'items', v_items
    )
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_checkout_payment_status(p_order_id integer, p_phone text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_phone text;
  v_order public.orders%ROWTYPE;
  v_payment public.payments%ROWTYPE;
BEGIN
  v_phone := public.normalize_ke_phone(p_phone);
  IF v_phone IS NULL OR p_order_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Missing order details');
  END IF;

  SELECT * INTO v_order
  FROM public.orders
  WHERE id = p_order_id
    AND public.normalize_ke_phone(phone) = v_phone;

  IF v_order.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Order not found');
  END IF;

  SELECT * INTO v_payment
  FROM public.payments
  WHERE order_id = v_order.id
  ORDER BY id DESC
  LIMIT 1;

  RETURN jsonb_build_object(
    'ok', true,
    'order_id', v_order.id,
    'order_number', v_order.order_number,
    'payment_status', v_order.payment_status,
    'order_status', v_order.status,
    'total', v_order.total_amount,
    'result_desc', v_payment.result_desc,
    'receipt', v_payment.transaction_id
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.prepare_mpesa_stk(
  p_order_id integer,
  p_contact_phone text,
  p_mpesa_phone text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_contact text;
  v_phone text;
  v_order public.orders%ROWTYPE;
  v_payment public.payments%ROWTYPE;
BEGIN
  v_contact := public.normalize_ke_phone(p_contact_phone);
  v_phone := public.normalize_ke_phone(coalesce(nullif(trim(p_mpesa_phone), ''), p_contact_phone));

  IF v_contact IS NULL OR v_phone IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Enter a valid M-Pesa number');
  END IF;

  SELECT * INTO v_order
  FROM public.orders
  WHERE id = p_order_id
    AND public.normalize_ke_phone(phone) = v_contact;

  IF v_order.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Order not found');
  END IF;

  IF lower(coalesce(v_order.payment_status, '')) IN ('paid', 'completed', 'success') THEN
    RETURN jsonb_build_object(
      'ok', true,
      'already_paid', true,
      'order_number', v_order.order_number,
      'amount', ceil(v_order.total_amount)
    );
  END IF;

  SELECT * INTO v_payment
  FROM public.payments
  WHERE order_id = v_order.id
  ORDER BY id DESC
  LIMIT 1;

  IF v_payment.stk_requested_at IS NOT NULL
     AND v_payment.stk_requested_at > now() - interval '20 seconds' THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', 'A payment prompt was just sent. Wait a moment before trying again.'
    );
  END IF;

  UPDATE public.payments
  SET phone = v_phone,
      stk_requested_at = now(),
      updated_at = now()
  WHERE id = v_payment.id;

  RETURN jsonb_build_object(
    'ok', true,
    'already_paid', false,
    'order_id', v_order.id,
    'order_number', v_order.order_number,
    'amount', ceil(v_order.total_amount)::integer,
    'msisdn', replace(v_phone, '+', ''),
    'account_reference', left(regexp_replace(v_order.order_number, '[^A-Za-z0-9]', '', 'g'), 12)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.complete_mpesa_stk(
  p_checkout_request_id text,
  p_merchant_request_id text,
  p_result_code integer,
  p_result_desc text,
  p_receipt text,
  p_payload jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_payment public.payments%ROWTYPE;
BEGIN
  IF nullif(trim(p_checkout_request_id), '') IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Missing checkout request');
  END IF;

  SELECT * INTO v_payment
  FROM public.payments
  WHERE checkout_request_id = trim(p_checkout_request_id)
  LIMIT 1;

  IF v_payment.id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'Unknown checkout request');
  END IF;

  IF p_result_code = 0 THEN
    UPDATE public.payments
    SET
      status = 'paid',
      transaction_id = coalesce(nullif(trim(p_receipt), ''), transaction_id),
      merchant_request_id = coalesce(nullif(trim(p_merchant_request_id), ''), merchant_request_id),
      result_desc = coalesce(p_result_desc, 'Paid'),
      mpesa_payload = coalesce(p_payload, mpesa_payload),
      updated_at = now()
    WHERE id = v_payment.id;

    UPDATE public.orders
    SET
      payment_status = 'paid',
      transaction_id = coalesce(nullif(trim(p_receipt), ''), transaction_id),
      updated_at = now()
    WHERE id = v_payment.order_id;

    RETURN jsonb_build_object('ok', true, 'paid', true, 'order_id', v_payment.order_id);
  END IF;

  UPDATE public.payments
  SET
    result_desc = coalesce(p_result_desc, 'Payment not completed'),
    merchant_request_id = coalesce(nullif(trim(p_merchant_request_id), ''), merchant_request_id),
    mpesa_payload = coalesce(p_payload, mpesa_payload),
    updated_at = now()
  WHERE id = v_payment.id;

  RETURN jsonb_build_object('ok', true, 'paid', false, 'order_id', v_payment.order_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.save_mpesa_stk_request(
  p_order_id integer,
  p_checkout_request_id text,
  p_merchant_request_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE public.payments
  SET
    checkout_request_id = nullif(trim(p_checkout_request_id), ''),
    merchant_request_id = nullif(trim(p_merchant_request_id), ''),
    stk_requested_at = now(),
    updated_at = now()
  WHERE id = (
    SELECT id FROM public.payments WHERE order_id = p_order_id ORDER BY id DESC LIMIT 1
  );

  RETURN jsonb_build_object('ok', true);
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_mpesa_provider_secrets()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'private'
AS $function$
DECLARE
  cfg private.mpesa_provider_config%ROWTYPE;
BEGIN
  SELECT * INTO cfg FROM private.mpesa_provider_config WHERE id = 1;

  RETURN jsonb_build_object(
    'environment', coalesce(cfg.environment, 'sandbox'),
    'consumer_key', coalesce(cfg.consumer_key, ''),
    'consumer_secret', coalesce(cfg.consumer_secret, ''),
    'shortcode', coalesce(cfg.shortcode, ''),
    'passkey', coalesce(cfg.passkey, ''),
    'party_type', coalesce(cfg.party_type, 'till')
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_mpesa_provider_status()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'private'
AS $function$
DECLARE
  cfg private.mpesa_provider_config%ROWTYPE;
BEGIN
  IF NOT public.is_staff() THEN
    RAISE EXCEPTION 'Only staff can view M-Pesa settings';
  END IF;

  SELECT * INTO cfg FROM private.mpesa_provider_config WHERE id = 1;

  RETURN jsonb_build_object(
    'configured',
      coalesce(cfg.consumer_key, '') <> ''
      AND coalesce(cfg.consumer_secret, '') <> ''
      AND coalesce(cfg.shortcode, '') <> ''
      AND coalesce(cfg.passkey, '') <> '',
    'environment', coalesce(cfg.environment, 'sandbox'),
    'shortcode', coalesce(cfg.shortcode, ''),
    'party_type', coalesce(cfg.party_type, 'till'),
    'consumer_key_set', coalesce(cfg.consumer_key, '') <> '',
    'has_secret', coalesce(cfg.consumer_secret, '') <> '',
    'has_passkey', coalesce(cfg.passkey, '') <> ''
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.save_mpesa_provider(
  p_environment text,
  p_consumer_key text,
  p_consumer_secret text,
  p_shortcode text,
  p_passkey text,
  p_party_type text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'private'
AS $function$
DECLARE
  v_env text;
  v_type text;
BEGIN
  IF NOT public.is_staff() THEN
    RAISE EXCEPTION 'Only staff can save M-Pesa settings';
  END IF;

  v_env := CASE WHEN lower(trim(coalesce(p_environment, ''))) = 'production' THEN 'production' ELSE 'sandbox' END;
  v_type := CASE WHEN lower(trim(coalesce(p_party_type, ''))) = 'paybill' THEN 'paybill' ELSE 'till' END;

  INSERT INTO private.mpesa_provider_config (
    id, environment, consumer_key, consumer_secret, shortcode, passkey, party_type, updated_at
  )
  VALUES (
    1,
    v_env,
    nullif(trim(p_consumer_key), ''),
    CASE
      WHEN coalesce(trim(p_consumer_secret), '') = '' THEN (
        SELECT consumer_secret FROM private.mpesa_provider_config WHERE id = 1
      )
      ELSE trim(p_consumer_secret)
    END,
    nullif(trim(p_shortcode), ''),
    CASE
      WHEN coalesce(trim(p_passkey), '') = '' THEN (
        SELECT passkey FROM private.mpesa_provider_config WHERE id = 1
      )
      ELSE trim(p_passkey)
    END,
    v_type,
    now()
  )
  ON CONFLICT (id) DO UPDATE
    SET environment = excluded.environment,
        consumer_key = excluded.consumer_key,
        consumer_secret = excluded.consumer_secret,
        shortcode = excluded.shortcode,
        passkey = excluded.passkey,
        party_type = excluded.party_type,
        updated_at = now();

  RETURN jsonb_build_object('ok', true);
END;
$function$;

REVOKE ALL ON FUNCTION public.get_mpesa_provider_secrets() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.prepare_mpesa_stk(integer, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.complete_mpesa_stk(text, text, integer, text, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.save_mpesa_stk_request(integer, text, text) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.get_mpesa_provider_secrets() TO service_role;
GRANT EXECUTE ON FUNCTION public.prepare_mpesa_stk(integer, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_mpesa_stk(text, text, integer, text, text, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.save_mpesa_stk_request(integer, text, text) TO service_role;

GRANT EXECUTE ON FUNCTION public.get_storefront_commerce() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.create_checkout_order(text, text, text, text, integer, text, text, text, jsonb, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.track_guest_order(text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_checkout_payment_status(integer, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_mpesa_provider_status() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.save_mpesa_provider(text, text, text, text, text, text) TO authenticated, service_role;
